#!/usr/bin/with-contenv sh

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket

cd /opt/airvideohd

exec s6-setuidgid airvideohd ./AirVideoServerHD --config=/etc/airvideohd/Server.properties



